name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## Changes
  $CHANGES
categories:
  - title: '🚀 Features'
    labels: ['feature','feat','enhancement']
  - title: '🐛 Fixes'
    labels: ['fix','bug']
  - title: '🧹 Chore'
    labels: ['chore','deps']
  - title: '🧪 Tests'
    labels: ['test']
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
