services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: biomath_core
      POSTGRES_USER: biomath
      POSTGRES_PASSWORD: biomath
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biomath -d biomath_core"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
