import {
  Brain,
  FlaskConical,
  Shield,
  Sun,
  Dumbbell,
  Stethoscope,
  HeartPulse,
  Microscope,
  Syringe,
  Activity,
  Apple,
  Moon,
} from "lucide-react";

export const CATEGORY_ICON: Record<string, any> = {
  "longevity-and-anti-aging": FlaskConical,
  "mental-wellness": Brain,
  "critical-health": Shield,
  "mens-health": Dumbbell,
  "everyday-wellness": Sun,
  "sleep-health": Moon,
  "metabolic-health": Apple,
  "cardio-health": HeartPulse,
  "lab-diagnostics": Microscope,
  vaccinations: Syringe,
  "fitness-performance": Activity,
  default: Stethoscope,
};

export const CATEGORY_COLOR: Record<string, string> = {
  "longevity-and-anti-aging": "text-teal-500 dark:text-teal-300",
  "mental-wellness": "text-indigo-600 dark:text-indigo-300",
  "critical-health": "text-rose-600 dark:text-rose-300",
  "mens-health": "text-blue-600 dark:text-blue-300",
  "everyday-wellness": "text-emerald-600 dark:text-emerald-300",
  "sleep-health": "text-sky-600 dark:text-sky-300",
  "metabolic-health": "text-amber-600 dark:text-amber-300",
  "cardio-health": "text-red-600 dark:text-red-300",
  "lab-diagnostics": "text-fuchsia-600 dark:text-fuchsia-300",
  vaccinations: "text-cyan-600 dark:text-cyan-300",
  "fitness-performance": "text-violet-600 dark:text-violet-300",
  "risk-insight": "text-slate-300 dark:text-slate-300",
  "lab-results-explainer": "text-fuchsia-400 dark:text-fuchsia-300",
  "drug-drug-interaction-checker": "text-slate-300 dark:text-slate-300",
  "symptom-analyzer": "text-slate-300 dark:text-slate-300",
  "chronic-disease-coach": "text-slate-300 dark:text-slate-300",
  "ai-medication-adherence": "text-slate-300 dark:text-slate-300",
  "care-cost-optimizer": "text-slate-300 dark:text-slate-300",
  "post-surgery-recovery-tracker": "text-slate-300 dark:text-slate-300",
  "clinical-trial-finder": "text-slate-300 dark:text-slate-300",
  "pre-surgery-readiness": "text-slate-300 dark:text-slate-300",
  "rare-disease-navigator": "text-slate-300 dark:text-slate-300",
  "smart-med-refill": "text-slate-300 dark:text-slate-300",
  "ai-pain-map": "text-slate-300 dark:text-slate-300",
  "vaccination-passport": "text-slate-300 dark:text-slate-300",
  "post-covid-planner": "text-slate-300 dark:text-slate-300",
  "genetic-disease-risk-prediction": "text-slate-300 dark:text-slate-300",
  "emergency-medical-profile": "text-slate-300 dark:text-slate-300",
  "remote-vitals-monitoring": "text-slate-300 dark:text-slate-300",
  "healthy-travel-kit": "text-slate-300 dark:text-slate-300",
  "goal-assistant": "text-slate-300 dark:text-slate-300",
  "daily-habit-tracker": "text-slate-300 dark:text-slate-300",
  "stress-reduction-guide": "text-slate-300 dark:text-slate-300",
  "energy-level-optimizer": "text-slate-300 dark:text-slate-300",
  "mind-body-connection-exercises": "text-indigo-400 dark:text-indigo-300",
  "positive-affirmation-generator": "text-slate-300 dark:text-slate-300",
  "gratitude-journal-prompts": "text-slate-300 dark:text-slate-300",
  "digital-wellbeing-score": "text-slate-300 dark:text-slate-300",
  "mindful-eating-assistant": "text-indigo-400 dark:text-indigo-300",
  "work-life-balance-advisor": "text-slate-300 dark:text-slate-300",
  "immunity-booster-plan": "text-cyan-400 dark:text-cyan-300",
  "mindful-breathing-exercises": "text-indigo-400 dark:text-indigo-300",
  "ergonomic-workspace-setup": "text-slate-300 dark:text-slate-300",
  "social-connection-tracker": "text-slate-300 dark:text-slate-300",
  "biological-age-factors": "text-slate-300 dark:text-slate-300",
  "polygenic-risk-viewer": "text-slate-300 dark:text-slate-300",
  "epigenetic-age-dashboard": "text-slate-300 dark:text-slate-300",
  "pharmacogenomics-matcher": "text-slate-300 dark:text-slate-300",
  "genetic-trait-explainer": "text-slate-300 dark:text-slate-300",
  "telomere-length-analysis": "text-slate-300 dark:text-slate-300",
  "nad-optimization-guide": "text-slate-300 dark:text-slate-300",
  "senolytics-recommendation": "text-blue-400 dark:text-blue-300",
  "mitochondrial-health-assessment": "text-blue-400 dark:text-blue-300",
  "longevity-diet-planner": "text-teal-400 dark:text-teal-300",
  "glycemic-control-advisor": "text-slate-300 dark:text-slate-300",
  "cellular-senescence-score": "text-slate-300 dark:text-slate-300",
  "microbiome-diversity-analysis": "text-slate-300 dark:text-slate-300",
  "longevity-gene-expression-report": "text-teal-400 dark:text-teal-300",
  "organ-age-assessment": "text-blue-400 dark:text-blue-300",
  "mindfulness-guide": "text-indigo-400 dark:text-indigo-300",
  "motivation-booster": "text-slate-300 dark:text-slate-300",
  "digital-detox-planner": "text-slate-300 dark:text-slate-300",
  "digital-gratitude-wall": "text-slate-300 dark:text-slate-300",
  "social-battery-prediction": "text-slate-300 dark:text-slate-300",
  "social-isolation-coach": "text-slate-300 dark:text-slate-300",
  "cognitive-performance-enhancer": "text-violet-400 dark:text-violet-300",
  "emotional-regulation-tools": "text-slate-300 dark:text-slate-300",
  "cognitive-behavioral-therapy-cbt-modules":
    "text-slate-300 dark:text-slate-300",
  "stress-hormone-tracker": "text-slate-300 dark:text-slate-300",
  "sleep-mood-connection-analysis": "text-indigo-400 dark:text-indigo-300",
  "fitness-and-performance": "text-violet-400 dark:text-violet-300",
  "personalized-meal-plan": "text-slate-300 dark:text-slate-300",
  "vo2-max-assessment": "text-blue-400 dark:text-blue-300",
  "workout-generator": "text-slate-300 dark:text-slate-300",
  "strength-plateau-breaker": "text-slate-300 dark:text-slate-300",
  "soft-tissue-release-map": "text-slate-300 dark:text-slate-300",
  "body-fat-trend-projection": "text-slate-300 dark:text-slate-300",
  "sport-specific-warm-up": "text-slate-300 dark:text-slate-300",
  "cycling-power-prediction": "text-slate-300 dark:text-slate-300",
  "2-minute-hrv-breathwork": "text-slate-300 dark:text-slate-300",
  "active-recovery-timer": "text-slate-300 dark:text-slate-300",
  "desk-stretch-breaks": "text-slate-300 dark:text-slate-300",
  "soft-tissue-map": "text-slate-300 dark:text-slate-300",
  "endurance-training-plan": "text-slate-300 dark:text-slate-300",
  "flexibility-and-mobility-guide": "text-slate-300 dark:text-slate-300",
  "post-workout-nutrition-guide": "text-amber-400 dark:text-amber-300",
  "injury-prevention-plan": "text-slate-300 dark:text-slate-300",
  "strength-and-conditioning-coach": "text-slate-300 dark:text-slate-300",
  "powerlifting-program-generator": "text-slate-300 dark:text-slate-300",
  "running-gait-analysis": "text-slate-300 dark:text-slate-300",
  "womens-health": "text-pink-400 dark:text-pink-300",
  "cycle-tracker": "text-slate-300 dark:text-slate-300",
  "pregnancy-timeline": "text-slate-300 dark:text-slate-300",
  "menopause-navigator": "text-blue-400 dark:text-blue-300",
  "breast-health-risk": "text-slate-300 dark:text-slate-300",
  "hormone-dashboard": "text-slate-300 dark:text-slate-300",
  "endometriosis-symptom-tracker": "text-slate-300 dark:text-slate-300",
  "pcos-guide": "text-slate-300 dark:text-slate-300",
  "pelvic-floor-exercise-plan": "text-slate-300 dark:text-slate-300",
  "androgen-dashboard": "text-slate-300 dark:text-slate-300",
  "prostate-risk-score": "text-slate-300 dark:text-slate-300",
  "fertility-tracker": "text-slate-300 dark:text-slate-300",
  "hair-loss-predictor": "text-slate-300 dark:text-slate-300",
  "performance-coach": "text-violet-400 dark:text-violet-300",
  "cardiovascular-risk-for-men": "text-rose-400 dark:text-rose-300",
  "male-hormone-optimization": "text-slate-300 dark:text-slate-300",
  "prostate-health-coach": "text-slate-300 dark:text-slate-300",
  "beauty-and-skincare": "text-fuchsia-400 dark:text-fuchsia-300",
  "ai-skincare-routine": "text-fuchsia-400 dark:text-fuchsia-300",
  "uv-damage-forecast": "text-slate-300 dark:text-slate-300",
  "digital-dermatology-scan": "text-slate-300 dark:text-slate-300",
  "hair-porosity-advisor": "text-slate-300 dark:text-slate-300",
  "cosmetic-barcode-scan": "text-slate-300 dark:text-slate-300",
  "facial-massage-routine": "text-slate-300 dark:text-slate-300",
  "ingredient-conflict": "text-slate-300 dark:text-slate-300",
  "hair-growth-predictor": "text-slate-300 dark:text-slate-300",
  "anti-aging-skincare-advisor": "text-teal-400 dark:text-teal-300",
  "sunscreen-recommendation-engine": "text-blue-400 dark:text-blue-300",
  "nutrition-and-diet": "text-amber-400 dark:text-amber-300",
  "smart-food-swaps": "text-slate-300 dark:text-slate-300",
  "remote-patient-monitoring-rpm": "text-slate-300 dark:text-slate-300",
  "hydration-formula": "text-slate-300 dark:text-slate-300",
  "nutrition-label-decoder": "text-amber-400 dark:text-amber-300",
  "budget-meal-kit-builder": "text-slate-300 dark:text-slate-300",
  "sodium-potassium-meter": "text-slate-300 dark:text-slate-300",
  "gut-microbiome-analyzer": "text-slate-300 dark:text-slate-300",
  "personalized-supplement-guide": "text-blue-400 dark:text-blue-300",
  "metabolic-rate-calculator": "text-slate-300 dark:text-slate-300",
  "food-sensitivity-tracker": "text-slate-300 dark:text-slate-300",
  "electrolyte-balance-advisor": "text-slate-300 dark:text-slate-300",
  "food-sustainability-score": "text-slate-300 dark:text-slate-300",
  "meal-prep-planner": "text-slate-300 dark:text-slate-300",
  "recipe-nutrient-analyzer": "text-slate-300 dark:text-slate-300",
  "hydration-goal-setter": "text-slate-300 dark:text-slate-300",
  "sleep-and-recovery": "text-indigo-400 dark:text-indigo-300",
  "blue-light-planner": "text-slate-300 dark:text-slate-300",
  "sleep-hygiene-coach": "text-indigo-400 dark:text-indigo-300",
  "circadian-light-guide": "text-slate-300 dark:text-slate-300",
  "sleep-apnea-screener": "text-indigo-400 dark:text-indigo-300",
  "micro-meditation-generator": "text-slate-300 dark:text-slate-300",
  "sleep-environment-optimizer": "text-indigo-400 dark:text-indigo-300",
  "guided-sleep-meditation": "text-indigo-400 dark:text-indigo-300",
  "dream-pattern-analysis": "text-slate-300 dark:text-slate-300",
  "environmental-health": "text-indigo-400 dark:text-indigo-300",
  "eco-routine-assessment": "text-blue-400 dark:text-blue-300",
  "environmental-exposure": "text-indigo-400 dark:text-indigo-300",
  "pollen-defense": "text-slate-300 dark:text-slate-300",
  "indoor-noise-map": "text-slate-300 dark:text-slate-300",
  "commute-calorie-optimizer": "text-slate-300 dark:text-slate-300",
  "home-air-quality-advisor": "text-slate-300 dark:text-slate-300",
  "water-quality-monitor": "text-slate-300 dark:text-slate-300",
  "mold-exposure-risk-assessment": "text-blue-400 dark:text-blue-300",
  "family-health": "text-cyan-400 dark:text-cyan-300",
  "family-medication-hub": "text-cyan-400 dark:text-cyan-300",
  "child-growth-tracker": "text-slate-300 dark:text-slate-300",
  "genetic-compatibility-screening": "text-slate-300 dark:text-slate-300",
  "family-wellness-challenge": "text-emerald-400 dark:text-emerald-300",
  "child-immunization-scheduler": "text-cyan-400 dark:text-cyan-300",
  "family-first-aid-guide": "text-cyan-400 dark:text-cyan-300",
  "sibling-health-comparison": "text-slate-300 dark:text-slate-300",
  "preventive-medicine-and-longevity": "text-teal-400 dark:text-teal-300",
  "personalized-cancer-screening": "text-slate-300 dark:text-slate-300",
  "cardiovascular-disease-prevention-plan": "text-rose-400 dark:text-rose-300",
  "neurodegenerative-risk-assessment": "text-blue-400 dark:text-blue-300",
  "inflammation-management-program": "text-blue-400 dark:text-blue-300",
  "immune-system-optimization": "text-cyan-400 dark:text-cyan-300",
  "health-and-wellness-risk-calculator":
    "text-emerald-400 dark:text-emerald-300",
  "diabetes-prevention-program": "text-slate-300 dark:text-slate-300",
  "metabolic-syndrome-monitor": "text-slate-300 dark:text-slate-300",
  "biohacking-and-performance": "text-violet-400 dark:text-violet-300",
  "nootropic-recommendation-engine": "text-blue-400 dark:text-blue-300",
  "cryotherapy-protocol-generator": "text-slate-300 dark:text-slate-300",
  "red-light-therapy-guide": "text-slate-300 dark:text-slate-300",
  "cold-exposure-training-plan": "text-slate-300 dark:text-slate-300",
  "intermittent-fasting-schedule": "text-slate-300 dark:text-slate-300",
  "biofeedback-training-modules": "text-slate-300 dark:text-slate-300",
  "neurofeedback-session-planner": "text-slate-300 dark:text-slate-300",
  "wearable-data-integrator": "text-slate-300 dark:text-slate-300",
  "personalized-recovery-modalities": "text-slate-300 dark:text-slate-300",
  "nootropic-stack-builder": "text-slate-300 dark:text-slate-300",
  "cold-exposure-protocol": "text-slate-300 dark:text-slate-300",
  "breathwork-optimizer": "text-slate-300 dark:text-slate-300",
  "cognitive-enhancement-plan": "text-blue-400 dark:text-blue-300",
  "intermittent-fasting-calculator": "text-slate-300 dark:text-slate-300",
  "dopamine-reset-protocol": "text-slate-300 dark:text-slate-300",
  "sensory-deprivation-guide": "text-slate-300 dark:text-slate-300",
  "biofeedback-training-for-focus": "text-slate-300 dark:text-slate-300",
  "senior-care": "text-orange-400 dark:text-orange-300",
  "senior-dashboard": "text-orange-400 dark:text-orange-300",
  "caregiver-portal": "text-slate-300 dark:text-slate-300",
  "fall-detection-alert": "text-slate-300 dark:text-slate-300",
  "medication-adherence": "text-slate-300 dark:text-slate-300",
  "voice-companion": "text-slate-300 dark:text-slate-300",
  "frailty-index": "text-slate-300 dark:text-slate-300",
  "medication-reminder-system": "text-indigo-400 dark:text-indigo-300",
  "fall-prevention-exercises": "text-slate-300 dark:text-slate-300",
  "cognitive-health-games": "text-slate-300 dark:text-slate-300",
  "eye-health-suite": "text-sky-400 dark:text-sky-300",
  "browser-vision-test": "text-slate-300 dark:text-slate-300",
  "retina-scan-ai": "text-slate-300 dark:text-slate-300",
  "blue-light-filter": "text-slate-300 dark:text-slate-300",
  "eye-exercise-reminders": "text-indigo-400 dark:text-indigo-300",
  "digital-therapeutics-store": "text-purple-400 dark:text-purple-300",
  "insomnia-cbt-i-app": "text-slate-300 dark:text-slate-300",
  "adhd-neuro-game": "text-slate-300 dark:text-slate-300",
  "anxiety-management-app": "text-blue-400 dark:text-blue-300",
  "chronic-pain-relief-vr": "text-slate-300 dark:text-slate-300",
  "ptsd-recovery-modules": "text-slate-300 dark:text-slate-300",
  "general-sexual-longevity": "text-teal-400 dark:text-teal-300",
  "libido-hormonal-optimization": "text-teal-400 dark:text-teal-300",
  "sexual-health-biomarkers": "text-teal-400 dark:text-teal-300",
  "aphrodisiac-nutrigenomics": "text-slate-300 dark:text-slate-300",
  "microbiome-and-sexuality": "text-teal-400 dark:text-teal-300",
  "neuroplasticity-and-libido": "text-teal-400 dark:text-teal-300",
  "stress-and-cortisol-management": "text-blue-400 dark:text-blue-300",
  "circadian-rhythms-and-sexuality": "text-teal-400 dark:text-teal-300",
  "physical-fitness-for-sexuality": "text-violet-400 dark:text-violet-300",
  "peptide-therapy-for-libido": "text-teal-400 dark:text-teal-300",
  "xenoestrogen-detoxification": "text-slate-300 dark:text-slate-300",
  "psychosexual-optimization": "text-teal-400 dark:text-teal-300",
  "partner-synchronization": "text-slate-300 dark:text-slate-300",
  "fertility-health-assessment": "text-blue-400 dark:text-blue-300",
  "hormone-balance-for-libido": "text-teal-400 dark:text-teal-300",
  "sexual-wellness-education": "text-emerald-400 dark:text-emerald-300",
  "relationship-communication-coach": "text-slate-300 dark:text-slate-300",
  "mens-sexual-health": "text-blue-400 dark:text-blue-300",
  "vascular-health-for-potency": "text-slate-300 dark:text-slate-300",
  "male-vitality-and-trt": "text-slate-300 dark:text-slate-300",
  "erectile-dysfunction-guide": "text-slate-300 dark:text-slate-300",
  "sperm-health-optimization": "text-slate-300 dark:text-slate-300",
  "womens-sexual-health": "text-pink-400 dark:text-pink-300",
  "female-hormonal-optimization": "text-slate-300 dark:text-slate-300",
  "libido-boosting-nutrition": "text-amber-400 dark:text-amber-300",
  "pelvic-health-program": "text-slate-300 dark:text-slate-300",
  "menopausal-intimacy-advisor": "text-blue-400 dark:text-blue-300",
  default: "text-slate-500 dark:text-slate-300",
};

export function CategoryTitle({
  cat,
}: {
  cat: { slug?: string; title: string };
}) {
  const slug = cat?.slug || "";
  const Icon = (CATEGORY_ICON as any)[slug] ?? CATEGORY_ICON.default;
  const color = (CATEGORY_COLOR as any)[slug] ?? CATEGORY_COLOR.default;
  return (
    <span className="inline-flex items-center gap-2">
      <Icon className={`h-4 w-4 ${color}`} />
      <span className={`${color}`}>
        <span className={`${color}`}>{cat.title}</span>
      </span>
    </span>
  );
}
