name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_OPTIONS: "--max_old_space_size=4096"
      DATABASE_URL: "postgresql://user:pass@localhost:5432/biomath_core?schema=public"
      NEXTAUTH_SECRET: "ci-nextauth-secret"
      NEXTAUTH_URL: "http://localhost:3000"
      STRIPE_SECRET_KEY: "sk_test_ci"
      STRIPE_WEBHOOK_SECRET: "whsec_ci"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
