name: CI Fastlane

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: biomath_core
          POSTGRES_USER: biomath
          POSTGRES_PASSWORD: biomath
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U biomath -d biomath_core"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      NODE_ENV: test
      PLAYWRIGHT_BASE_URL: http://localhost:3000
      DATABASE_URL: postgresql://biomath:biomath@127.0.0.1:5432/biomath_core

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Ensure psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          for i in {1..60}; do
            pg_isready -h 127.0.0.1 -p 5432 -U biomath -d biomath_core && break || sleep 1
          done

      - name: Prisma generate
        run: pnpm prisma generate

      - name: Prisma migrate deploy
        run: pnpm prisma migrate deploy || true

      - name: Seed (best-effort)
        run: pnpm run db:seed || true

      - name: Unit tests
        run: pnpm run test:unit

      - name: E2E smoke (Playwright)
        run: pnpm exec playwright test --config=tests/e2e/smoke.config.ts

      - name: Upload Playwright report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e/playwright-report
          if-no-files-found: ignore
