name: CI
on:
  pull_request:
    branches: [ "main-2", "release/**", "refactor/**" ]
  push:
    branches: [ "main-2", "release/**", "refactor/**" ]
jobs:
  freeze-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Freeze guard
        run: |
          base="${{ github.base_ref }}"
          [ -z "$base" ] && base="${{ github.event.pull_request.base.ref }}"
          CHANGED=$(git diff --name-only origin/$base...HEAD || true)
          FROZEN=$(cat <<'EOF'
src/app/member/
src/components/ai/
src/components/Header.tsx
src/components/Footer.tsx
src/app/admin/
src/app/monitoring/
src/app/control-center/
EOF
)
          touched=""
          for p in $FROZEN; do
            echo "$CHANGED" | grep -E "^$p" >/dev/null && touched=1
          done
          if [ "$touched" = "1" ]; then
            echo "${{ github.event.pull_request.body }}" | grep -qi "UNFREEZE-APPROVED" || { echo "Frozen area changed without UNFREEZE-APPROVED"; exit 1; }
          fi
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
