name: docker
on:
  push:
    branches: [main-1]
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          SHA=${{ github.sha }}
          BRANCH=${GITHUB_REF_NAME//\//-}
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tags=$IMAGE:latest,$IMAGE:${BRANCH},$IMAGE:${SHA::12}" >> $GITHUB_OUTPUT

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.image }}:buildcache
          cache-to: type=registry,ref=${{ steps.meta.outputs.image }}:buildcache,mode=max
