name: E2E
on:
  workflow_dispatch:
  push:
    branches: [main-2]

jobs:
  e2e:
    name: e2e (${{ matrix.browser }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ms-playwright-

      - name: Install Playwright browsers + system deps
        run: pnpm exec playwright install --with-deps ${{ matrix.browser }}
        timeout-minutes: 30

      - name: Run E2E (${{ matrix.browser }})
        run: pnpm exec playwright test --project=${{ matrix.browser }} --reporter=github,html
        timeout-minutes: 30

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-e2e-report-${{ matrix.browser }}
          path: playwright-report
          retention-days: 14
