name: E2E
on:
  workflow_dispatch:
  push:
    branches:
      - main-2

jobs:
  e2e:
    name: e2e (${{ matrix.browser }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Install Playwright deps
        uses: microsoft/playwright-github-action@v1
        timeout-minutes: 25

      - name: Run E2E (${{ matrix.browser }})
        run: pnpm exec playwright test --project=${{ matrix.browser }} --reporter=html,github

      - name: Upload failure assets
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-assets-${{ matrix.browser }}
          path: |
            test-results/**/*.zip
            test-results/**/*.png
            test-results/**/*.webm
          retention-days: 7

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-e2e-report-${{ matrix.browser }}
          path: playwright-report
          retention-days: 14
