name: member-guard
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, feature/member-**, hotfix/member-**, member-zone-stable-** ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: freeze-check
        run: |
          if [ "${{ github.ref_name }}" != "main" ] && ! [[ "${{ github.ref_name }}" =~ ^(feature/member-|hotfix/member-|member-zone-stable-) ]]; then
            CHANGED=$(git diff --name-only origin/main...HEAD -- 'src/app/member/**' 'src/app/catalog/**' 'src/components/**' 'src/lib/**' || true)
            if [ -n "$CHANGED" ]; then
              echo "$CHANGED"
              exit 1
            fi
          fi
      - run: pnpm build
      - run: NEXT_DISABLE_ESLINT=1 pnpm start -- -p 3000 &
      - run: npx wait-on http://localhost:3000
      - run: pnpm test:routes
