name: Vercel Preview

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_OPTIONS: "--max_old_space_size=4096"
      PLAYWRIGHT_BASE_URL: "http://localhost:3000"
      DATABASE_URL: "postgresql://user:pass@localhost:5432/biomath_core?schema=public"
      NEXTAUTH_SECRET: "ci-nextauth-secret"
      NEXTAUTH_URL: "http://localhost:3000"
      STRIPE_SECRET_KEY: "sk_test_ci"
      STRIPE_WEBHOOK_SECRET: "whsec_ci"
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.16.1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build

      - name: Pull Vercel env
        uses: vercel/actions/pull@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}

      - name: Deploy to Vercel (preview)
        id: deploy
        uses: vercel/actions/deploy@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          environment: preview
          alias-domains: ""
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Comment Preview URL
        if: steps.deploy.outputs.preview-url
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.deploy.outputs.preview-url }}';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `Preview: ${url}`
            });
